#!/usr/bin/env python3
"""Generate PS-side assets for the Gemma3-600K accelerator:
   * sw/vocab.h - token-id -> piece (bytes+len) table from golden/gemma3_tok1024.bin,
                  plus the precomputed prompt token ids (greedy longest-match encode)
                  so the bare-metal PS only needs to decode, not tokenize.
   model.bin (the fp16 weight blob) is produced by script/gen_blob.py.
Run:  python gen_assets.py
"""
import os, struct
HERE = os.path.dirname(os.path.abspath(__file__))
GOLD = os.path.normpath(os.path.join(HERE, "..", "golden"))
SW   = os.path.join(HERE, "sw")
os.makedirs(SW, exist_ok=True)

raw = open(os.path.join(GOLD, "gemma3_tok1024.bin"), "rb").read()
(vocab_size,) = struct.unpack("<I", raw[:4])
offs = list(struct.unpack("<%dI" % (vocab_size + 1), raw[4:4 + 4*(vocab_size+1)]))
body = raw[4 + 4*(vocab_size+1):]
pieces = [body[offs[i]:offs[i+1]] for i in range(vocab_size)]
max_len = max(len(p) for p in pieces)

def c_escape(b: bytes) -> str:
    out = []
    for c in b:
        if c == 0x22:   out.append('\\"')
        elif c == 0x5c: out.append('\\\\')
        elif c == 0x0a: out.append('\\n')
        elif c == 0x09: out.append('\\t')
        elif c == 0x0d: out.append('\\r')
        elif 0x20 <= c < 0x7f: out.append(chr(c))
        else: out.append('\\x%02x' % c)
    return ''.join(out)

def encode(text, bos=True):
    b = text.encode("utf-8"); toks = []
    if bos: toks.append(2)
    pos = 0
    while pos < len(b):
        best_id, best_len = -1, 0
        for i in range(4, vocab_size):
            p = pieces[i]; ln = len(p)
            if ln > best_len and b[pos:pos+ln] == p:
                best_id, best_len = i, ln
                if best_len == max_len: break
        if best_id < 0: best_id, best_len = 3, 1
        toks.append(best_id); pos += best_len
    return toks

PROMPT = "The little robot lived in the red shed. Every morning it rolled across the floor. One day "
ptoks = encode(PROMPT, bos=True)

hdr = os.path.join(SW, "vocab.h")
with open(hdr, "w") as f:
    f.write("// auto-generated by gen_assets.py from golden/gemma3_tok1024.bin\n")
    f.write("#ifndef VOCAB_H\n#define VOCAB_H\n")
    f.write(f"#define VOCAB_SIZE {vocab_size}\n")
    f.write(f"#define MAX_PIECE {max_len}\n")
    f.write("static const char *vocab[VOCAB_SIZE] = {\n")
    for i, p in enumerate(pieces):
        f.write(f'  /*{i:4d}*/ "{c_escape(p)}",\n')
    f.write("};\n")
    f.write("static const unsigned char vocab_len[VOCAB_SIZE] = {\n  ")
    f.write(", ".join(str(len(p)) for p in pieces))
    f.write("\n};\n")
    f.write(f"#define N_PROMPT {len(ptoks)}\n")
    f.write("static const int prompt_tokens[N_PROMPT] = {\n  ")
    f.write(", ".join(str(t) for t in ptoks))
    f.write("\n};\n")
    f.write('static const char *prompt_text = "' + c_escape(PROMPT.encode()) + '";\n')
    f.write("#endif\n")
print(f"vocab.h: {vocab_size} tokens, max_piece={max_len}, prompt={len(ptoks)} tokens -> {ptoks}")
